Ocp-Apim-Subscription-Key='9c95cff1e0cd40f38a9959358360a069'
access_token='f00d'
;base_url='https://localhost:7169/api'
base_url='https://foodmeterapiapi.azure-api.net/api'
api_key="sk-proj-B5xgceBZ4GA3uqyYEsSJT3BlbkFJfMRIYn2qiSj7aGNYkExV"